//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwisspel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anwser
    {
        public int id { get; set; }
        public int Quizzes_id { get; set; }
        public int Questions_id { get; set; }
        public int QuestionOptions_id { get; set; }
    
        public virtual QuestionOption QuestionOption { get; set; }
        public virtual Question Question { get; set; }
        public virtual Quizze Quizze { get; set; }
    }
}
